name: Build Docker image

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 1 * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build SDK base image
        run: ./scripts/build-sdk-base.sh

      - name: Build NDK base image
        run: ./scripts/build-ndk-base.sh

      - name: Build platform images
        run: ./scripts/build-platform-images.sh
